### ISSUE TITLE
Detect unexported func parameters that always receive the same value

### ISSUE THREAD

**Issue by mvdan** [mvdan/unparam#11]
A rather different check to what this tool usually does. But it seems in the "unnecessary parameter" realm like unused parameters.

**Comment by shurcooL** [comment]
Can you clarify/be more precise about what you mean by "same value"? Identical value per execution? At all times? Constant? Etc.

**Comment by mvdan** [comment]
I was vague on purpose - I'm not sure what the limit is with SSA et al. Constants is the obvious first step.

Need to play with it :) this issue was more of a note to self, since I found a case manually in code of mine.

**Comment by mvdan** [comment]
I ended up going just for consts - see commit above.
