### ISSUE TITLE
detect cases where no caller uses a return value

### ISSUE THREAD

**Issue by kevinburke** [mvdan/unparam#16]
Via https://go-review.googlesource.com/c/55232, the signature of `lookupName` is:

```go
func (l *Location) lookupName(name string, unix int64) (offset int, isDST bool, ok bool) {
```

But the only caller has this:

```go
offset, _, ok := local.lookupName(zoneName, t.unixSec())
```

If every caller discards a return parameter, we could probably avoid using it in the function signature. (This would be difficult to implement, apparently)

**Comment by mvdan** [comment]
Well, the case of return parameters always assigned to underscore is not difficult. But some aspects aren't trivial:

* Should we treat `error` return parameters differently?
* If there are callers hidden behind build tags, we should take them into account too (not sure how; we don't have them in the ssa program)
* What if return prameters aren't discarded, but still unused? (e.g. used as an unused parameter or in a dead assignment)

I'll have a look at this in a few days once I'm back from holidays.

**Comment by mvdan** [comment]
@kevinburke PTAL at the tool after these changes (and the code, if you wish).

Your case is covered:

```
/home/mvdan/tip/src/time/zoneinfo.go:111:64: result isDST is always unused
```

I'll send a CL now with a couple of other changes like that one - I'll add you in the CC.

I looked around for a bit but I couldn't see any obvious false positives. Let me know if you find any.
