### ISSUE TITLE
Detect return parameters that always have the same value

### ISSUE THREAD

**Issue by mvdan** [mvdan/unparam#17]
We can start with constants. For example:

```
func foo() int {
    if someCond() {
        return 2
    }
    return 2
}
```

**Comment by kevinburke** [comment]
Sure, or bools I guess as well... though imagine

```go
if someCond() {
    time.Sleep()
    return 2
}
return 2
```

I guess in each case we can still omit the return value if it doesn't change.

**Comment by mvdan** [comment]
@kevinburke I'm not sure if I understand your comment - this rule would apply to your example too.

**Comment by kevinburke** [comment]
whoops ignore me :(
