### ISSUE TITLE
Unnamed parameters and test doubles 

### ISSUE THREAD

**Issue by gonzaloserrano** [mvdan/unparam#19]
Hi,

First: congrats, this tool is very nice!

Second, I'd like to discuss a common case scenario in the projects I work with.

Let's say we have an interface:
```
type x interface {
    func y(a int, b string) error
}
```
Sometimes I have a dummy implementation of this interface in a test where some (or all) parameters are not used. What I thought is that making them not used explicitly could be achieved unamming those params, like:
```
func (m myType) y(int, string) error {
    // no names ___^_____^ 
    // do nothing
    return nil
} 
```

To not trigger an unparam error, maybe some flag could be added so if the param does not have  a name then it wouldn't error.

What do you think?

**Comment by mvdan** [comment]
Hi @gonzaloserrano!

The tool already ignores parameters that are unnamed, i.e. if the name is `""` or `"_"`. Here are the corresponding tests:

https://github.com/mvdan/unparam/blob/master/check/testdata/names.go

If you find that the tool still has any false positives, please report them.

Also note that you don't always have to remove the names or use `_` for unused parameters. For example, if you're implementing an interface and have to keep them around, `unparam` should also ignore them even if they have names. Here are those tests:

https://github.com/mvdan/unparam/blob/master/check/testdata/impl.go

**Comment by mvdan** [comment]
Also, if you want to check what parameters from what files in those tests are warnings, you can see the expected log here: https://github.com/mvdan/unparam/blob/master/check/testdata/log

**Comment by gonzaloserrano** [comment]
You are right, somehow I missed it yesterday when testing the tool, but now I've tried it and it behaves as you said.

Thanks!
