### ISSUE TITLE
Ignore funcs that get func call values as parameters?

### ISSUE THREAD

**Issue by mvdan** [mvdan/unparam#2]
```
func Foo(a, b int) {
    println(a)
}

func Bar() (int, int) {
    return 2, 3
}

func main() {
    Foo(Bar())
}
```

Should we report the unused `b` parameter in `Foo`? Right now we do.

Points in favor of doing it:

* Technically an unused parameter
* Code can be rewritten to accomodate, e.g. `a, _ := Bar(); Foo(a)`
* Simpler linter implementation, as we don't need to look at func calls

Disadvantages:

* Unlike the rest of the current warnings, the suggested change is more intrusive

What I mean by more intrusive is, say, if besides `Foo` we have `Foo2` which does use both parameters. We would make the actuall calls to `Foo` and `Foo2` different, whereas they were almost the same before.

I tend to think we should do the suggestion, but not 100% sure.

**Comment by damienstanton** [comment]
I agree that it should be reported. I would rather be alerted that I've defined a signature with an unused parameter, even if that means changing callers down the line.

**Comment by mvdan** [comment]
Thanks for the input (you too, sneaky @shurcool). After thinking about it for a couple of days, I too am convinced that it should be reported. Haven't been able to find a reason not to other than "it slightly bothers the developer". But it's still a valid suggestion.
