### ISSUE TITLE
Flag to ignore unused error return parameters

### ISSUE THREAD

**Issue by tehsphinx** [mvdan/unparam#20]
Hi Daniel!

When designing a function I want to return an error that can occur. Often I do not use that error however as it does not matter in that situation. Then unparam flags that as an unused parameter.

It would be nice to have the option to ignore unused error return parameters.

A typical example would be a Close() function with an error returned. Most of the time I don't care if I was able to close something or not.

PS: Cool stuff you make here!

**Comment by tehsphinx** [comment]
additional reason for me to switch this off is: I also run errcheck linter and it already tells me if I ignore errors.

**Comment by mvdan** [comment]
Could you provide a small example and the output that the tool gives?

**Comment by mvdan** [comment]
I'm in general against flags and ways to circumvent warnings manually. It does seem like an unused error result warning tends to be less useful because of the error type.

However, I see a different issue here. This warning should not have been there as you are implementing `io.Closer`. I'll fix this, and let's see if that would be enough. Ignoring all error returns is a bit of a nuclear option.

**Comment by tehsphinx** [comment]
My personal opinion: I think all unsused errors should be ignored. I would not have my developers remove unused error parameters just to satisfy this linter. I would rather have them use the error parameters and think hard before not using them. This is done by other linters such as https://github.com/kisielk/errcheck.

Since `unparam` linter complains about returned error parameters that are not used rather than function calls that do not check the error we are not using it any more.

**Comment by mvdan** [comment]
@tehsphinx thanks for the input - will keep it in mind :)

I have been planning a partial rewrite/redesign of `unparam` since it has a couple of flaws deep down. I'll work on this issue along with those, and let you know what I come up with.

**Comment by mvdan** [comment]
Ended up agreeing with you, especially because I struggle to see how that warning would ever be useful with error returns.

**Comment by tehsphinx** [comment]
Cool, man!

I will enable unparam for my projects again and see what I get :)
