### ISSUE TITLE
unparam does not support build tags

### ISSUE THREAD

**Issue by benpaxton-hf** [mvdan/unparam#22]
`unparam` currently doesn't support build tags, which means packages which require a non-implicit build tag can't be linted, e.g.:

`main.go`
```go
package main

import (
	"./sub"
	"fmt"
)

func main() {
	fmt.Printf("Hello, %s!\n", sub.Get())
}
```
`sub/sub_a.go`
```go
//+build a

package sub

func Get() string {
	return "world"
}
```
`sub/sub_b.go`
```go
//+build b

package sub

func Get() string {
	return "everyone"
}
```
`sub/sub.go`
```go
package sub

// some shared code
```

```
$ ls
main.go  sub
$ unparam .
.../main.go:9:29: Get not declared by package sub
couldn't load packages due to errors: .
$ go run -tags a main.go 
Hello, world!
$ go run -tags b main.go 
Hello, everyone!
```

**Comment by mvdan** [comment]
Good point - this needs to be added.

Ideally, there would be a way to check all tag combinations without having to multiply the amount of work. I have no idea how to do that, though.

**Comment by benpaxton-hf** [comment]
Checking all tag combinations is probably impossible without knowing what they mean - in my example case, for example, `a b` and `!a !b` are not valid - only `a !b` and `!a b` are valid tag combinations.

If `unparam -tags a .` worked, though, it'd be easy to use external tools to enumerate valid tag combinations and lint each, e.g.
```make
lint-unparam:
    unparam -tags a .
    unparam -tags b .
```

**Comment by shurcooL** [comment]
In case this is helpful, see https://github.com/mdempsky/unconvert/pull/27/files for an example of how this can be implemented.

**Comment by mvdan** [comment]
@shurcooL thanks, that just saved me a good ten minutes of furious head-scratching.

**Comment by mvdan** [comment]
Also, jesus, the help output is bad:

```
 $ unparam -h
usage: unparam [flags] [package ...]
  -debug
        debug prints
  -exported
        inspect exported functions
  -tags build tags
        a list of build tags to consider satisfied during the build. For more information about build tags, see the description of build constraints in the documentation for the go/build package
  -tests
        include tests (default true)
```

I've filed https://github.com/golang/go/issues/23464 about this.

**Comment by shurcooL** [comment]
FYI, according to https://speakerdeck.com/campoy/the-state-of-go-1-dot-10?slide=23, there have been some improvements to the `flags` package in Go 1.10 to make its output more readable.

P.S. Friendly ping on resolving this issue. I would've liked to use it today:

```
$ unparam -tags=dev ./...
flag provided but not defined: -tags
```

**Comment by mvdan** [comment]
Thanks for the ping - I got sidetracked on this.
