### ISSUE TITLE
Compatibility issue with go <1.8

### ISSUE THREAD

**Issue by szuecs** [mvdan/unparam#3]
I would like to have unparam merged into gometalinter and it will not be integrated if it is not backward compatible reference to goetmalinter issue: https://github.com/alecthomas/gometalinter/issues/256
The issue is that sort.Slice is only available in go >= 1.8, not as int gometalinter issue described sort.Sort.

Would be nice to have unparam merged there. 
Great work, thanks!

**Comment by mvdan** [comment]
I usually keep compatibility with two minor Go versions (in this case 1.7 and 1.8), but I was lazy and hadn't gotten around to it with this project yet.

Thanks for reporting!

**Comment by mvdan** [comment]
Done - 1.7 support fixed and added to Travis.

**Comment by szuecs** [comment]
Thanks!
