### ISSUE TITLE
Assigning an unused parameter to a blank identifier doesn't make it used.

### ISSUE THREAD

**Issue by dmitshur** [mvdan/unparam#32]
This seems like an unintentional behavior, but please correct me otherwise.

In most other contests, assigning something to the blank identifier makes it used. It's often used to "force" a use to avoid compilation errors, when there's no other normal use because the code is in development.

This doesn't seem to work for `unparam`. Consider the program:

```Go
package p

import "fmt"

func foo(v string) {
	fmt.Println("this does some stuff")
	fmt.Println("not a stub, etc.")
	if true {
		fmt.Println("really, there's complex logic!")
	}

	_ = v // TODO: Actually use v.
}
```

I would expect the `_ = v` line to cause `v` to be marked as "used" and not get printed as an unused parameter, but that's not what happens with latest `unparam`:

```
$ unparam
main.go:5:10: foo - v is unused
```

Or are there good reasons why assigning to a blank identifier should not be considered a "use"? /cc @dominikh

**Comment by mvdan** [comment]
You're right - this should make the tool quiet. Might not be easy to do though, since the tool works almost entirely on SSA.

**Comment by mvdan** [comment]
I had a quick crack at it, but `_ = v` is indeed gone from the final SSA. I'm not sure what the best approach here is.

The simplest solution is to go through the function's syntax tree and detect all statements of the form `_ = some-parameter`. However, this won't detect other syntactic variants, such as `var _ = some-parameter` or `_, _ = some-parameter, some-parameter-2`.

Another solution would be to check if a parameter is used zero times in the SSA body, but non-zero times in the syntax tree body. This, in theory, should cover cases like `if false { use(v) }` on top of the ones described above.

I'm leaning towards the second solution, which should be the most generic while still being simple to maintain.
