### ISSUE TITLE
Issue on function that have parameters that shouldn't be removed

### ISSUE THREAD

**Issue by mavimo** [mvdan/unparam#35]
## Type

Bug report

## Current

Actually when I try to validate a command created using [`cobra` CLI library](github.com/spf13/cobra) I receive a failure for unused param, eg:

```golang
package main

import (
	"github.com/spf13/cobra"
)

func main() {
	rootCmd.Execute()
}

var rootCmd = &cobra.Command{
	Use:   "demo",
	Short: "demo",
	Run: func(cmd *cobra.Command, args []string) {
		cmd.Usage()
	},
}
```
Generate:
```
main.go:14:32: init$1 - args is unused
```
but since the `Run` is a function that need args we can't skip it.

Command with debug flag report:
```
func init$1
parameter cmd : *github.com/spf13/cobra.Command
  skip - used somewhere in the func body
parameter args : []string
func main
main.go:14:32: init$1 - args is unused
```

## Expected

No issue detected

## Additional note

This behaviour seems an issue added some days ago, since was working "as expected" some day ago: https://travis-ci.org/mavimo/hetzner-kube/jobs/441696541#L554 but is broken now https://travis-ci.org/mavimo/hetzner-kube/jobs/447106130#L504

**Comment by mvdan** [comment]
Thanks for the bug report and the minimal repro. The scenario seems simple enough, but it may be tricky to translate that to code.
