### ISSUE TITLE
Flags necessary elements of function signature

### ISSUE THREAD

**Issue by akerl** [mvdan/unparam#36]
Looking at https://github.com/akerl/voyager/blob/b3c2a92371cac8d4a59d5f058d71e3cc011c9310/prompt/wmenu.go#L17-L20 , I get the following error:

```
~/.go/src/github.com/akerl/voyager/prompt master*
❯ unparam -debug
func WithWmenu$1
parameter opts : []github.com/akerl/voyager/vendor/github.com/dixonwille/wmenu.Opt
  skip - used somewhere in the func body
wmenu.go:17:39: WithWmenu$1 - result 0 (error) is always nil
```

The code in question:

```
	menu.Action(func(opts []wmenu.Opt) error {
		c <- opts[0].ID
		return nil
	})
````

While it's correct that I'm not ever setting the return to something other than nil, the error is a crucial part of the function signature, given that it's needed by `menu.Action()`

**Comment by mvdan** [comment]
Thanks for reporting. Seems like a clear false positive.

**Comment by mvdan** [comment]
Actually very similar to #35. Will try to fix both together.

**Comment by mvdan** [comment]
Fixed - please shout if you find any other false positives.
