### ISSUE TITLE
Go-RPC

### ISSUE THREAD

**Issue by 1995parham** [mvdan/unparam#38]
Go-RPC needs methods return error but sometimes there is no error with the method and `unparam` create an error. Consider the following method as an example:

```go
// Multiply multiplies given parameters and stores it result
func (t *Arith) Multiply(args *Args, reply *int) error {
	*reply = args.A * args.B
	return nil
}
```

**Comment by mvdan** [comment]
Could you please provide a full program which reproduces this false positive?

**Comment by 1995parham** [comment]
You can find it [here](https://github.com/1995parham/Learning/blob/7cdc5e2325c7c467f7d1b9c978683aea95666c66/Go/go-rpc/main.go). I lint this program with [golangci-lint](https://github.com/golangci/golangci-lint) and get the false positive error.

**Comment by mvdan** [comment]
Thanks. `net/rpc` is completely reflect-based, which is probably why we're not seeing that. We could probably ignore all types passed to `net/rpc.Register`.
