### ISSUE TITLE
Possible to ignore stubbed functions?

### ISSUE THREAD

**Issue by ansermino** [mvdan/unparam#39]
Is there anyway I can ignore stubbed functions? Specifically when they return errors? Here's an example:
```
func futureFeature(x int, y int) (z int, err error) {
   _, _ = x, y
    return 0, nil
}
```
This will warn me that `err` is always nil. I don't want to change the function signature as that would take away from the benefits of stubbing. There is no interface this function is adhering to so it won't get ignored.

**Comment by mvdan** [comment]
Stub functions should be skipped; does this still happen if you remove the `_, _ = x, y` line?

**Comment by ansermino** [comment]
Then it warms me about the unused params. Is there a specific way it determines if a function is stubbed?

**Comment by mvdan** [comment]
Sorry, I can't reproduce either problem.

```
$ cat f1.go
package p

func f(x int, y int) (z int, err error) {
        _, _ = x, y
        return 0, nil
}
$ unparam f1.go
$ cat f2.go
package p

func f(x int, y int) (z int, err error) {
        return 0, nil
}
$ unparam f2.go
```

Are you sure you're running the latest version from master?

**Comment by mvdan** [comment]
No answer; closing.
