### ISSUE TITLE
goreleaser: error: unknown long flag '--snapshot', try --help

### ISSUE THREAD

**Issue by dzpao** [mvdan/unparam#44]
Are there any updates recently? The github actions are broken.

See also:
https://github.com/mudclient/go-mud/runs/436203136?check_suite_focus=true#step:5:26

workflow:
https://github.com/mudclient/go-mud/actions/runs/37026103/workflow

**Comment by mvdan** [comment]
How is this related to unparam? I don't use goreleaser at all.

**Comment by dzpao** [comment]
Sorry, I sent it in the wrong place.
