### ISSUE TITLE
main package has no godoc

### ISSUE THREAD

**Issue by dmitshur** [mvdan/unparam#46]
[Effective Go](https://golang.org/doc/effective_go.html#commentary) says:

> Every package should have a package comment, a block comment preceding the package clause.

The command `mvdan.cc/unparam` does not have a package comment.

This can be seen by visiting https://pkg.go.dev/mvdan.cc/unparam or running `go doc mvdan.cc/unparam` inside the module.

**Comment by mvdan** [comment]
I know what a package doc is :) I just need to get in the habit of copying the same first sentence between the README and package doc. Seems low priority.
