### ISSUE TITLE
Possible to skip directories through flag?

### ISSUE THREAD

**Issue by zodac** [mvdan/unparam#48]
I'm running unparam through golangci-lint. One of my packages has some issues, and I'd like to skip that for the unparam check, but leave it for the remaining ones.

Is this possible with the existing flags?

**Comment by mvdan** [comment]
You can give unparam the packages you want it to check. If you want to only check a subset of the packages, you can do that too, like:

```
unparam $(go list ./... | grep -v /badpkg)
```

If you want flags to filter the input packages or results directly, I think tools like golangci-lint will already have that sort of thing. I don't think it's worth reimplementing that stuff in each separate tool.
