### ISSUE TITLE
Common linter interface

### ISSUE THREAD

**Issue by mvdan** [mvdan/unparam#5]
I propose that all Go linters that work on vanilla `x/tools/go/loader` (`go/ast` + `go/types`) and `x/tools/go/ssa` implement an interface, to allow running multiple of them at once while sharing parsing, type-checking and SSA work.

The interface could be something like:

```
type Checker interface{
    Check(*loader.Program, *ssa.Program) ([]Warning, error)
}

type Warning struct {
    Pos token.Pos
    Msg string
}
```

Each linter would have an importable package with a type satisfying this interface.

**Comment by bradleyfalzon** [comment]
Perhaps calling it Issue instead of Warning, this way whether the linter refers to the problem as an informational, warning or error, Issue still sounds appropriate.

**Comment by thomasheller** [comment]
If there was a generic `Warning` struct that most linters used, we could also get rid of the [regex parsing of linter output in gometalinter](https://github.com/alecthomas/gometalinter/blob/c521f922c5c23ed8f3adf342dfab8997cae52e3c/config.go#L106) eventually.

**Comment by mvdan** [comment]
@bradleyfalzon I'm not too concerned about the names at the moment - `Checker` could also be `Linter` for example. I'm more concerned about whether the current interface is powerful enough to accomodate for all the current linters. For mine, it is.

**Comment by bradleyfalzon** [comment]
Yeah sorry, perhaps my comment was a little premature.

Perhaps this is a good discussion to bring up in https://github.com/kisielk/gotool as some of the linters (https://godoc.org/github.com/kisielk/gotool?importers) use this library to support their argument list (`./...` etc)? If this proposal requires a concrete type, then perhaps gotool is a good place for it?

**Comment by mvdan** [comment]
That sounds fine to me - as long as the interface is backwards compatible and the repo is managed by the community, it's not too important where the canonical definition is.

**Comment by mvdan** [comment]
Then again, `gotool` isn't only for linters, and its purpose is already defined and simple. IMO it should be a separate repository.

I've created https://github.com/mvdan/lint. Let's move discussion there - separate issues for separate improvements/discussions on the design. I'm not going to open a "general discussion" issue like this one, at least for now.

**Comment by shurcooL** [comment]
> `gotool` isn't only for linters, and its purpose is already defined and simple. IMO it should be a separate repository.

Strongly agreed.

**Comment by mvdan** [comment]
Also, for any of you who have your own linters, I've just added a very simple `cmd/metacheck` in that repo with just one of my linters for now. Things are still in the early stages and may change quite a bit, but PRs are welcome to add more linters.
