### ISSUE TITLE
this value of err is never used (SA4006)

### ISSUE THREAD

**Issue by 89z** [mvdan/unparam#61]
Using this program:

~~~go
package hello
import "strconv"

type private int

func Public() (private, error) {
   n, err := strconv.Atoi("99")
   if err != nil {
      return 0, err
   }
   _, err = strconv.Atoi("88")
   return private(n), nil
}
~~~

With other tools [1], I get this error:

~~~
this value of err is never used (SA4006)
~~~

but nothing with UnParam. I am trying to find something that works with Go 1.18.

1. https://github.com/dominikh/go-tools

**Comment by mvdan** [comment]
unparam is meant to warn you when a parameter in a function is never used. It does not look at when the values returned by functions aren't used properly. Staticcheck has "value is never used" checks, and that's fine - that's separate from what unparam does.

**Comment by 89z** [comment]
> It does not look at when the values returned by functions aren't used properly.

Sorry, I think I misunderstood this quote from the README:

> It also reports results that always return the same value, parameters that always receive the same value, and results that are never used.

Isnt my case "results that are never used"?

**Comment by mvdan** [comment]
I guess the wording could be clearer, but unparam only looks at results which are never assigned to a variable or passed along, like `_, _ = Public()`. It does not track unused values, which is a completely different kind of analysis. And one that staticcheck already implements, anyway :)

**Comment by 89z** [comment]
Thanks for the feedback. Do you know anything like StaticCheck, that works with Go 1.18? StaticCheck is completely broken when used with Go 1.18 `go` command.
