### ISSUE TITLE
An option to ignore parameters starting with the underscore (e.g., `_name`)?

### ISSUE THREAD

**Issue by favonia** [mvdan/unparam#67]
I wonder if it makes sense to add an option to ignore _function_ parameters that start with the underscore (not just _method_ parameters)? I found them useful for commenting purpose (for otherwise it is unclear what that argument might be), and I would like to keep these unused parameters so that a group of functions would share the same type. This choice also seems consistent with the variable checking used by `revive`.

**Comment by mvdan** [comment]
Sure, that seems fine. Want to send a PR with a test?

**Comment by favonia** [comment]
Not right now---I just used up my FOSS time for October. :-)
