### ISSUE TITLE
Be smarter about what func signatures to ignore

### ISSUE THREAD

**Issue by mvdan** [mvdan/unparam#7]
For example, if both a named signature and a func are unexported, we could look at the package's source code to check that the func is never used as that signature:

```
package foo

type t func(path string) // if this is removed, str is flagged.

func f(str string) {
        println("")
}
```

Other extra analysis could be added to fix some false negatives, probably. Ideas welcome.

Forked from #6.

**Comment by bradleyfalzon** [comment]
Just for my understanding, what's the purpose of excluding functions that match a function type?

**Comment by mvdan** [comment]
See my first code snippet at https://github.com/mvdan/unparam/issues/6#issuecomment-292923014. The same applies for imported packages (e.g. if you import and use `filepath.WalkFunc`) and with interfaces.

For interfaces, we could limit the scope to ignoring methods, and not funcs. But we would have to be careful about:

```
func methodImpl(...) { }

func (t *T) actualMethod(...) { methodImpl(...) }
```

**Comment by mvdan** [comment]
We now ignore unexported type signatures, so the example in the original thread is fixed.

I'll work on improving the heuristics, but I'll leave issues to specific examples of false positives and negatives.
