### ISSUE TITLE
Bump golang.org/x/tools to v0.7.0 (as minimum) and make new tag 

### ISSUE THREAD

**Issue by Antonboom** [mvdan/unparam#73]
Hi 🙂

Please, bump `golang.org/x/tools` to v0.7.0 (as minimum) and make new tag in your repo.

It's important to support new 1.20 **golangci-lint.**
Related to https://github.com/golangci/golangci-lint/issues/3086

Thanks!

P.S. Optionally I recommend

- [ ] to move linter to 1.20 totally (go.mod, CI, etc.)
- [ ] add support of [dependabot](https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/)

**Comment by Antonboom** [comment]
UPD:

Sorry, false-positive, don't see usage of `buildssa.Analyzer`.
But pay attention anyway :)

**Comment by mvdan** [comment]
I do keep my deps reasonably up to date, but for what it's worth, unparam should work OK with Go 1.20. Especially since downstreams can update dependencies like x/tools via MVS.

I definitely don't want to add dependabot. It's noisy to the point of being a waste of time.
